name: auto merge
on: pull_request
jobs:
  merge:
    if: ${{github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: dependabot/fetch-metadata@v2
      - run: gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
        if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch'}}
